// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package amux_ctrl_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 2;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {logic [4:0] q;} amux_ctrl_reg2hw_sel_reg_t;

  // Register -> HW type
  typedef struct packed {
    amux_ctrl_reg2hw_sel_reg_t sel;  // [4:0]
  } amux_ctrl_reg2hw_t;

  // Register offsets
  parameter logic [BlockAw-1:0] AMUX_CTRL_SEL_OFFSET = 2'h0;

  // Register index
  typedef enum int {AMUX_CTRL_SEL} amux_ctrl_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] AMUX_CTRL_PERMIT[1] = '{
      4'b0001  // index[0] AMUX_CTRL_SEL
  };

endpackage

