// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module refs_ctrl_reg_top #(
    parameter type reg_req_t = logic,
    parameter type reg_rsp_t = logic,
    parameter int AW = 4
) (
    input logic clk_i,
    input logic rst_ni,
    input reg_req_t reg_req_i,
    output reg_rsp_t reg_rsp_o,
    // To HW
    output refs_ctrl_reg_pkg::refs_ctrl_reg2hw_t reg2hw,  // Write


    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);

  import refs_ctrl_reg_pkg::*;

  localparam int DW = 32;
  localparam int DBW = DW / 8;  // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [ AW-1:0] reg_addr;
  logic [ DW-1:0] reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [ DW-1:0] reg_rdata;
  logic           reg_error;

  logic addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t reg_intf_req;
  reg_rsp_t reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [9:0] iref1_calibration_qs;
  logic [9:0] iref1_calibration_wd;
  logic iref1_calibration_we;
  logic [9:0] iref2_calibration_qs;
  logic [9:0] iref2_calibration_wd;
  logic iref2_calibration_we;
  logic [4:0] vref_calibration_qs;
  logic [4:0] vref_calibration_wd;
  logic vref_calibration_we;

  // Register instances
  // R[iref1_calibration]: V(False)

  prim_subreg #(
      .DW      (10),
      .SWACCESS("RW"),
      .RESVAL  (10'h0)
  ) u_iref1_calibration (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(iref1_calibration_we),
      .wd(iref1_calibration_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.iref1_calibration.q),

      // to register interface (read)
      .qs(iref1_calibration_qs)
  );


  // R[iref2_calibration]: V(False)

  prim_subreg #(
      .DW      (10),
      .SWACCESS("RW"),
      .RESVAL  (10'h0)
  ) u_iref2_calibration (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(iref2_calibration_we),
      .wd(iref2_calibration_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.iref2_calibration.q),

      // to register interface (read)
      .qs(iref2_calibration_qs)
  );


  // R[vref_calibration]: V(False)

  prim_subreg #(
      .DW      (5),
      .SWACCESS("RW"),
      .RESVAL  (5'h0)
  ) u_vref_calibration (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(vref_calibration_we),
      .wd(vref_calibration_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.vref_calibration.q),

      // to register interface (read)
      .qs(vref_calibration_qs)
  );




  logic [2:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == REFS_CTRL_IREF1_CALIBRATION_OFFSET);
    addr_hit[1] = (reg_addr == REFS_CTRL_IREF2_CALIBRATION_OFFSET);
    addr_hit[2] = (reg_addr == REFS_CTRL_VREF_CALIBRATION_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(REFS_CTRL_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(REFS_CTRL_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(REFS_CTRL_PERMIT[2] & ~reg_be)))));
  end

  assign iref1_calibration_we = addr_hit[0] & reg_we & !reg_error;
  assign iref1_calibration_wd = reg_wdata[9:0];

  assign iref2_calibration_we = addr_hit[1] & reg_we & !reg_error;
  assign iref2_calibration_wd = reg_wdata[9:0];

  assign vref_calibration_we  = addr_hit[2] & reg_we & !reg_error;
  assign vref_calibration_wd  = reg_wdata[4:0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[9:0] = iref1_calibration_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[9:0] = iref2_calibration_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[4:0] = vref_calibration_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module refs_ctrl_reg_top_intf #(
    parameter  int AW = 4,
    localparam int DW = 32
) (
    input logic clk_i,
    input logic rst_ni,
    REG_BUS.in regbus_slave,
    // To HW
    output refs_ctrl_reg_pkg::refs_ctrl_reg2hw_t reg2hw,  // Write
    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);
  localparam int unsigned STRB_WIDTH = DW / 8;

  `include "register_interface/typedef.svh"
  `include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;

  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)



  refs_ctrl_reg_top #(
      .reg_req_t(reg_bus_req_t),
      .reg_rsp_t(reg_bus_rsp_t),
      .AW(AW)
  ) i_regs (
      .clk_i,
      .rst_ni,
      .reg_req_i(s_reg_req),
      .reg_rsp_o(s_reg_rsp),
      .reg2hw,  // Write
      .devmode_i
  );

endmodule


