// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module ses_filter_reg_top #(
    parameter type reg_req_t = logic,
    parameter type reg_rsp_t = logic,
    parameter int AW = 5
) (
    input logic clk_i,
    input logic rst_ni,
    input reg_req_t reg_req_i,
    output reg_rsp_t reg_rsp_o,

    // Output port for window
    output reg_req_t [1-1:0] reg_req_win_o,
    input  reg_rsp_t [1-1:0] reg_rsp_win_i,

    // To HW
    output ses_filter_reg_pkg::ses_filter_reg2hw_t reg2hw,  // Write
    input  ses_filter_reg_pkg::ses_filter_hw2reg_t hw2reg,  // Read


    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);

  import ses_filter_reg_pkg::*;

  localparam int DW = 32;
  localparam int DBW = DW / 8;  // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [ AW-1:0] reg_addr;
  logic [ DW-1:0] reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [ DW-1:0] reg_rdata;
  logic           reg_error;

  logic addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t reg_intf_req;
  reg_rsp_t reg_intf_rsp;


  logic [0:0] reg_steer;

  reg_req_t [2-1:0] reg_intf_demux_req;
  reg_rsp_t [2-1:0] reg_intf_demux_rsp;

  // demux connection
  assign reg_intf_req = reg_intf_demux_req[1];
  assign reg_intf_demux_rsp[1] = reg_intf_rsp;

  assign reg_req_win_o[0] = reg_intf_demux_req[0];
  assign reg_intf_demux_rsp[0] = reg_rsp_win_i[0];

  // Create Socket_1n
  reg_demux #(
      .NoPorts(2),
      .req_t  (reg_req_t),
      .rsp_t  (reg_rsp_t)
  ) i_reg_demux (
      .clk_i,
      .rst_ni,
      .in_req_i(reg_req_i),
      .in_rsp_o(reg_rsp_o),
      .out_req_o(reg_intf_demux_req),
      .out_rsp_i(reg_intf_demux_rsp),
      .in_select_i(reg_steer)
  );


  // Create steering logic
  always_comb begin
    reg_steer = 1;  // Default set to register

    // TODO: Can below codes be unique case () inside ?
    if (reg_req_i.addr[AW-1:0] >= 28) begin
      reg_steer = 0;
    end
  end


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic ses_control_qs;
  logic ses_control_wd;
  logic ses_control_we;
  logic [1:0] ses_status_qs;
  logic [4:0] ses_window_size_qs;
  logic [4:0] ses_window_size_wd;
  logic ses_window_size_we;
  logic [9:0] ses_decim_factor_qs;
  logic [9:0] ses_decim_factor_wd;
  logic ses_decim_factor_we;
  logic [9:0] ses_sysclk_division_qs;
  logic [9:0] ses_sysclk_division_wd;
  logic ses_sysclk_division_we;
  logic [5:0] ses_activated_stages_qs;
  logic [5:0] ses_activated_stages_wd;
  logic ses_activated_stages_we;
  logic [4:0] ses_gain_stage_gain_stg_0_qs;
  logic [4:0] ses_gain_stage_gain_stg_0_wd;
  logic ses_gain_stage_gain_stg_0_we;
  logic [4:0] ses_gain_stage_gain_stg_1_qs;
  logic [4:0] ses_gain_stage_gain_stg_1_wd;
  logic ses_gain_stage_gain_stg_1_we;
  logic [4:0] ses_gain_stage_gain_stg_2_qs;
  logic [4:0] ses_gain_stage_gain_stg_2_wd;
  logic ses_gain_stage_gain_stg_2_we;
  logic [4:0] ses_gain_stage_gain_stg_3_qs;
  logic [4:0] ses_gain_stage_gain_stg_3_wd;
  logic ses_gain_stage_gain_stg_3_we;
  logic [4:0] ses_gain_stage_gain_stg_4_qs;
  logic [4:0] ses_gain_stage_gain_stg_4_wd;
  logic ses_gain_stage_gain_stg_4_we;
  logic [4:0] ses_gain_stage_gain_stg_5_qs;
  logic [4:0] ses_gain_stage_gain_stg_5_wd;
  logic ses_gain_stage_gain_stg_5_we;

  // Register instances
  // R[ses_control]: V(False)

  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_ses_control (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(ses_control_we),
      .wd(ses_control_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.ses_control.q),

      // to register interface (read)
      .qs(ses_control_qs)
  );


  // R[ses_status]: V(False)

  prim_subreg #(
      .DW      (2),
      .SWACCESS("RO"),
      .RESVAL  (2'h0)
  ) u_ses_status (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.ses_status.de),
      .d (hw2reg.ses_status.d),

      // to internal hardware
      .qe(),
      .q (),

      // to register interface (read)
      .qs(ses_status_qs)
  );


  // R[ses_window_size]: V(False)

  prim_subreg #(
      .DW      (5),
      .SWACCESS("RW"),
      .RESVAL  (5'h0)
  ) u_ses_window_size (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(ses_window_size_we),
      .wd(ses_window_size_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.ses_window_size.q),

      // to register interface (read)
      .qs(ses_window_size_qs)
  );


  // R[ses_decim_factor]: V(False)

  prim_subreg #(
      .DW      (10),
      .SWACCESS("RW"),
      .RESVAL  (10'h0)
  ) u_ses_decim_factor (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(ses_decim_factor_we),
      .wd(ses_decim_factor_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.ses_decim_factor.q),

      // to register interface (read)
      .qs(ses_decim_factor_qs)
  );


  // R[ses_sysclk_division]: V(False)

  prim_subreg #(
      .DW      (10),
      .SWACCESS("RW"),
      .RESVAL  (10'h0)
  ) u_ses_sysclk_division (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(ses_sysclk_division_we),
      .wd(ses_sysclk_division_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.ses_sysclk_division.q),

      // to register interface (read)
      .qs(ses_sysclk_division_qs)
  );


  // R[ses_activated_stages]: V(False)

  prim_subreg #(
      .DW      (6),
      .SWACCESS("RW"),
      .RESVAL  (6'h0)
  ) u_ses_activated_stages (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(ses_activated_stages_we),
      .wd(ses_activated_stages_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.ses_activated_stages.q),

      // to register interface (read)
      .qs(ses_activated_stages_qs)
  );


  // R[ses_gain_stage]: V(False)

  //   F[gain_stg_0]: 4:0
  prim_subreg #(
      .DW      (5),
      .SWACCESS("RW"),
      .RESVAL  (5'h0)
  ) u_ses_gain_stage_gain_stg_0 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(ses_gain_stage_gain_stg_0_we),
      .wd(ses_gain_stage_gain_stg_0_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.ses_gain_stage.gain_stg_0.q),

      // to register interface (read)
      .qs(ses_gain_stage_gain_stg_0_qs)
  );


  //   F[gain_stg_1]: 9:5
  prim_subreg #(
      .DW      (5),
      .SWACCESS("RW"),
      .RESVAL  (5'h0)
  ) u_ses_gain_stage_gain_stg_1 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(ses_gain_stage_gain_stg_1_we),
      .wd(ses_gain_stage_gain_stg_1_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.ses_gain_stage.gain_stg_1.q),

      // to register interface (read)
      .qs(ses_gain_stage_gain_stg_1_qs)
  );


  //   F[gain_stg_2]: 14:10
  prim_subreg #(
      .DW      (5),
      .SWACCESS("RW"),
      .RESVAL  (5'h0)
  ) u_ses_gain_stage_gain_stg_2 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(ses_gain_stage_gain_stg_2_we),
      .wd(ses_gain_stage_gain_stg_2_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.ses_gain_stage.gain_stg_2.q),

      // to register interface (read)
      .qs(ses_gain_stage_gain_stg_2_qs)
  );


  //   F[gain_stg_3]: 19:15
  prim_subreg #(
      .DW      (5),
      .SWACCESS("RW"),
      .RESVAL  (5'h0)
  ) u_ses_gain_stage_gain_stg_3 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(ses_gain_stage_gain_stg_3_we),
      .wd(ses_gain_stage_gain_stg_3_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.ses_gain_stage.gain_stg_3.q),

      // to register interface (read)
      .qs(ses_gain_stage_gain_stg_3_qs)
  );


  //   F[gain_stg_4]: 24:20
  prim_subreg #(
      .DW      (5),
      .SWACCESS("RW"),
      .RESVAL  (5'h0)
  ) u_ses_gain_stage_gain_stg_4 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(ses_gain_stage_gain_stg_4_we),
      .wd(ses_gain_stage_gain_stg_4_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.ses_gain_stage.gain_stg_4.q),

      // to register interface (read)
      .qs(ses_gain_stage_gain_stg_4_qs)
  );


  //   F[gain_stg_5]: 29:25
  prim_subreg #(
      .DW      (5),
      .SWACCESS("RW"),
      .RESVAL  (5'h0)
  ) u_ses_gain_stage_gain_stg_5 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(ses_gain_stage_gain_stg_5_we),
      .wd(ses_gain_stage_gain_stg_5_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.ses_gain_stage.gain_stg_5.q),

      // to register interface (read)
      .qs(ses_gain_stage_gain_stg_5_qs)
  );




  logic [6:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == SES_FILTER_SES_CONTROL_OFFSET);
    addr_hit[1] = (reg_addr == SES_FILTER_SES_STATUS_OFFSET);
    addr_hit[2] = (reg_addr == SES_FILTER_SES_WINDOW_SIZE_OFFSET);
    addr_hit[3] = (reg_addr == SES_FILTER_SES_DECIM_FACTOR_OFFSET);
    addr_hit[4] = (reg_addr == SES_FILTER_SES_SYSCLK_DIVISION_OFFSET);
    addr_hit[5] = (reg_addr == SES_FILTER_SES_ACTIVATED_STAGES_OFFSET);
    addr_hit[6] = (reg_addr == SES_FILTER_SES_GAIN_STAGE_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(SES_FILTER_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(SES_FILTER_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(SES_FILTER_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(SES_FILTER_PERMIT[3] & ~reg_be))) |
               (addr_hit[4] & (|(SES_FILTER_PERMIT[4] & ~reg_be))) |
               (addr_hit[5] & (|(SES_FILTER_PERMIT[5] & ~reg_be))) |
               (addr_hit[6] & (|(SES_FILTER_PERMIT[6] & ~reg_be)))));
  end

  assign ses_control_we = addr_hit[0] & reg_we & !reg_error;
  assign ses_control_wd = reg_wdata[0];

  assign ses_window_size_we = addr_hit[2] & reg_we & !reg_error;
  assign ses_window_size_wd = reg_wdata[4:0];

  assign ses_decim_factor_we = addr_hit[3] & reg_we & !reg_error;
  assign ses_decim_factor_wd = reg_wdata[9:0];

  assign ses_sysclk_division_we = addr_hit[4] & reg_we & !reg_error;
  assign ses_sysclk_division_wd = reg_wdata[9:0];

  assign ses_activated_stages_we = addr_hit[5] & reg_we & !reg_error;
  assign ses_activated_stages_wd = reg_wdata[5:0];

  assign ses_gain_stage_gain_stg_0_we = addr_hit[6] & reg_we & !reg_error;
  assign ses_gain_stage_gain_stg_0_wd = reg_wdata[4:0];

  assign ses_gain_stage_gain_stg_1_we = addr_hit[6] & reg_we & !reg_error;
  assign ses_gain_stage_gain_stg_1_wd = reg_wdata[9:5];

  assign ses_gain_stage_gain_stg_2_we = addr_hit[6] & reg_we & !reg_error;
  assign ses_gain_stage_gain_stg_2_wd = reg_wdata[14:10];

  assign ses_gain_stage_gain_stg_3_we = addr_hit[6] & reg_we & !reg_error;
  assign ses_gain_stage_gain_stg_3_wd = reg_wdata[19:15];

  assign ses_gain_stage_gain_stg_4_we = addr_hit[6] & reg_we & !reg_error;
  assign ses_gain_stage_gain_stg_4_wd = reg_wdata[24:20];

  assign ses_gain_stage_gain_stg_5_we = addr_hit[6] & reg_we & !reg_error;
  assign ses_gain_stage_gain_stg_5_wd = reg_wdata[29:25];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = ses_control_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[1:0] = ses_status_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[4:0] = ses_window_size_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[9:0] = ses_decim_factor_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[9:0] = ses_sysclk_division_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[5:0] = ses_activated_stages_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[4:0]   = ses_gain_stage_gain_stg_0_qs;
        reg_rdata_next[9:5]   = ses_gain_stage_gain_stg_1_qs;
        reg_rdata_next[14:10] = ses_gain_stage_gain_stg_2_qs;
        reg_rdata_next[19:15] = ses_gain_stage_gain_stg_3_qs;
        reg_rdata_next[24:20] = ses_gain_stage_gain_stg_4_qs;
        reg_rdata_next[29:25] = ses_gain_stage_gain_stg_5_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module ses_filter_reg_top_intf #(
    parameter  int AW = 5,
    localparam int DW = 32
) (
    input logic clk_i,
    input logic rst_ni,
    REG_BUS.in regbus_slave,
    REG_BUS.out regbus_win_mst[1-1:0],
    // To HW
    output ses_filter_reg_pkg::ses_filter_reg2hw_t reg2hw,  // Write
    input ses_filter_reg_pkg::ses_filter_hw2reg_t hw2reg,  // Read
    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);
  localparam int unsigned STRB_WIDTH = DW / 8;

  `include "register_interface/typedef.svh"
  `include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;

  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  reg_bus_req_t s_reg_win_req[1-1:0];
  reg_bus_rsp_t s_reg_win_rsp[1-1:0];
  for (genvar i = 0; i < 1; i++) begin : gen_assign_window_structs
    `REG_BUS_ASSIGN_TO_REQ(s_reg_win_req[i], regbus_win_mst[i])
    `REG_BUS_ASSIGN_FROM_RSP(regbus_win_mst[i], s_reg_win_rsp[i])
  end



  ses_filter_reg_top #(
      .reg_req_t(reg_bus_req_t),
      .reg_rsp_t(reg_bus_rsp_t),
      .AW(AW)
  ) i_regs (
      .clk_i,
      .rst_ni,
      .reg_req_i(s_reg_req),
      .reg_rsp_o(s_reg_rsp),
      .reg_req_win_o(s_reg_win_req),
      .reg_rsp_win_i(s_reg_win_rsp),
      .reg2hw,  // Write
      .hw2reg,  // Read
      .devmode_i
  );

endmodule


