#!/bin/bash
# Copyright 2021 OpenHW Group
# Solderpad Hardware License, Version 2.1, see LICENSE.md for details.
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1

find hw/ip hw/simulation tb  -name '*.sv*' | xargs verible-verilog-format --column_limit 150 --inplace 2> /dev/zero
